language: php

php:
  - 7.3

services:
  - redis-server

addons:
  mariadb: '10.3'

install:
  - travis_retry composer install --no-interaction --prefer-source

env:
  - DB_USER=root
  - DB_PASS=

before_script:
  - mysql -e "create database IF NOT EXISTS trnsltr;" -uroot;
  - cp .env.example .env
  - vendor/bin/phinx migrate

script:
  - vendor/bin/phpunit --verbose --coverage-text --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
