language: php

php:
  - 7.3

services:
  - redis-server

install:
  - travis_retry composer install --no-interaction --prefer-source

before_script:
  - cp .env.example .env

script:
  - vendor/bin/phpunit --verbose --coverage-text --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
