version: '3'

services:
    server:
        image: nginx:latest
        ports:
            - "8081:8081"
            - "443:443"
        volumes:
            - ./src:/usr/share/nginx/html
            - ./docker/site.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
    php:
        image: edbizarro/gitlab-ci-pipeline-php:7.3-fpm
        volumes:
            - ./src:/usr/share/nginx/html
            - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
        working_dir: /usr/share/nginx/html
        tty: true
    redis:
        image: redis:latest
